/**
 * Baichuan crypto primitives — TypeScript port of the conformance-tested Dart/Python core.
 *
 * Pure JS (spark-md5 + aes-js) so it runs unchanged in React Native (Hermes has no Node `crypto`)
 * and in Node for the fixture tests. Every function here is checked byte-for-byte against
 * `__fixtures__/fixtures.json` (generated by the installer repo's bc_fixtures.py) in crypto.test.ts.
 * The three traps that cost days during development are called out inline.
 */
import SparkMD5 from 'spark-md5';
import aesjs from 'aes-js';

const enc = new TextEncoder();

/** TRAP 1: the vendor truncates the MD5 hex to 31 chars, not 32. A 32-char hash fails auth. */
export function md5Modern(s: string): string {
  const buf = enc.encode(s);
  // Hash the UTF-8 BYTES (SparkMD5.hash(str) would treat the string as a binary/UTF-16 blob).
  const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
  const hex = SparkMD5.ArrayBuffer.hash(ab); // 32-char lowercase
  return hex.slice(0, 31).toUpperCase();
}

const XML_KEY = [0x1f, 0x2d, 0x3c, 0x4b, 0x5a, 0x69, 0x78, 0xff];

/** BC-XOR cipher. Offset is ch_id (250 for host). Used for the login body and 1466 replies. */
export function bcXor(buf: Uint8Array, offset: number): Uint8Array {
  const off = ((offset % 256) + 256) % 256;
  const out = new Uint8Array(buf.length);
  for (let i = 0; i < buf.length; i++) {
    out[i] = buf[i] ^ XML_KEY[(off + i) % 8] ^ off;
  }
  return out;
}

const AES_IV = enc.encode('0123456789abcdef'); // 16 ASCII bytes, fixed IV

/**
 * TRAP 2: CFB *128*, not CFB8 — built from the raw AES block function so no library default can
 * silently differ. TRAP 3: `key` is the ASCII bytes of a 16-char hex-looking string, already
 * AES-128 length; it is NOT that string hex-decoded.
 */
function cfb128(key: Uint8Array, data: Uint8Array, encrypt: boolean): Uint8Array {
  const aes = new aesjs.AES(key); // ECB single-block, always in the ENCRYPT direction
  const out = new Uint8Array(data.length);
  let prev = new Uint8Array(AES_IV);
  for (let i = 0; i < data.length; i += 16) {
    // aes-js returns a Uint8Array at runtime; its typings widen to a non-indexable ByteSource.
    const ks = aes.encrypt(prev) as unknown as Uint8Array; // 16-byte keystream
    const n = Math.min(16, data.length - i);
    for (let j = 0; j < n; j++) out[i + j] = data[i + j] ^ ks[j];
    // feedback is the CIPHERTEXT block in both directions
    const fb = new Uint8Array(16);
    for (let j = 0; j < n; j++) fb[j] = encrypt ? out[i + j] : data[i + j];
    prev = fb;
  }
  return out;
}

export const aesEncrypt = (key: Uint8Array, body: Uint8Array): Uint8Array => cfb128(key, body, true);
export const aesDecrypt = (key: Uint8Array, data: Uint8Array): Uint8Array => cfb128(key, data, false);

/** Session AES key. Note the LITERAL HYPHEN between nonce and password (absent from the hashes). */
export function deriveAesKey(nonce: string, password: string): Uint8Array {
  return enc.encode(md5Modern(`${nonce}-${password}`).slice(0, 16));
}

/** Hex helpers (RN-safe). */
export function toHex(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += b.toString(16).padStart(2, '0');
  return s;
}
export function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
  return out;
}
